
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jefry Hernandez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_casa = new javax.swing.JDialog();
        tf_nombrecasa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_casa = new javax.swing.JTextArea();
        jp_nivelcasa = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jd_cancha = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jt_nombrecan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_direccioncan = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        sp_seguridadcan = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        cb_categoriacan = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        rb_libre = new javax.swing.JRadioButton();
        rb_ocupado = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jd_carretera = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        sp_distancia = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        cb_inicio = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cb_termina = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jd_restaurante = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_direccionresta = new javax.swing.JTextArea();
        jp_nivelres = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tf_nombreres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_categoriares = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        rbg_estado = new javax.swing.ButtonGroup();
        jd_jtree = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        cb_jtree = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_listar = new javax.swing.JTree();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jd_jtable = new javax.swing.JDialog();
        cb_jtable = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_tabla = new javax.swing.JTable();
        jd_list = new javax.swing.JDialog();
        cb_list = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_List = new javax.swing.JList<>();
        jLabel24 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        carret = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jLabel1.setText("Creacion de casa");

        jLabel2.setText("Nombre");

        jLabel3.setText("Direccion");

        ta_casa.setColumns(20);
        ta_casa.setRows(5);
        jScrollPane1.setViewportView(ta_casa);

        jp_nivelcasa.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        jp_nivelcasa.setAutoscrolls(true);

        jLabel4.setText("Nivel de seguridad");

        jButton1.setText("Crear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_casaLayout = new javax.swing.GroupLayout(jd_casa.getContentPane());
        jd_casa.getContentPane().setLayout(jd_casaLayout);
        jd_casaLayout.setHorizontalGroup(
            jd_casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_casaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jd_casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_casaLayout.createSequentialGroup()
                        .addGroup(jd_casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(jd_casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombrecasa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_casaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34)
                        .addGroup(jd_casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jp_nivelcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jd_casaLayout.setVerticalGroup(
            jd_casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_casaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jd_casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombrecasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jd_casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_casaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jd_casaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jd_casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jp_nivelcasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        jLabel10.setText("Creacion de cancha");

        jLabel11.setText("Nombre");

        jLabel12.setText("Direccion");

        ta_direccioncan.setColumns(20);
        ta_direccioncan.setRows(5);
        jScrollPane3.setViewportView(ta_direccioncan);

        jLabel13.setText("Nivel de seguridad");

        sp_seguridadcan.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        jLabel14.setText("Categoria");

        cb_categoriacan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Football", "Basquet", "Tennis", "Volley" }));

        jLabel15.setText("Estado");

        rbg_estado.add(rb_libre);
        rb_libre.setText("Libre");

        rbg_estado.add(rb_ocupado);
        rb_ocupado.setText("Ocupado");

        jButton3.setText("Crear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_canchaLayout = new javax.swing.GroupLayout(jd_cancha.getContentPane());
        jd_cancha.getContentPane().setLayout(jd_canchaLayout);
        jd_canchaLayout.setHorizontalGroup(
            jd_canchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_canchaLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jd_canchaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_canchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_canchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_canchaLayout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(cb_categoriacan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel14))
                    .addGroup(jd_canchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_canchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(jd_canchaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(43, 43, 43)
                                .addComponent(jt_nombrecan, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jd_canchaLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(37, 37, 37)
                            .addGroup(jd_canchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_canchaLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(29, 29, 29)
                                    .addComponent(sp_seguridadcan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_canchaLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(27, 27, 27)
                        .addComponent(rb_libre)
                        .addGap(18, 18, 18)
                        .addComponent(rb_ocupado)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jd_canchaLayout.setVerticalGroup(
            jd_canchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_canchaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(23, 23, 23)
                .addGroup(jd_canchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jt_nombrecan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_canchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_canchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(sp_seguridadcan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jd_canchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cb_categoriacan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_canchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(rb_libre)
                    .addComponent(rb_ocupado))
                .addGap(31, 31, 31)
                .addComponent(jButton3))
        );

        jLabel16.setText("Crear carretera");

        jLabel17.setText("Codigo");

        jLabel18.setText(cont+"");

        jLabel19.setText("Distancia");

        sp_distancia.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jLabel20.setText("Lugar de inicio");

        cb_inicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_inicioItemStateChanged(evt);
            }
        });
        cb_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_inicioActionPerformed(evt);
            }
        });

        jLabel21.setText("Lugar que termina");

        jButton4.setText("Crear");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_carreteraLayout = new javax.swing.GroupLayout(jd_carretera.getContentPane());
        jd_carretera.getContentPane().setLayout(jd_carreteraLayout);
        jd_carreteraLayout.setHorizontalGroup(
            jd_carreteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_carreteraLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jd_carreteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_inicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jd_carreteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_carreteraLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jd_carreteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jd_carreteraLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jd_carreteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_termina, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(141, Short.MAX_VALUE))))
            .addGroup(jd_carreteraLayout.createSequentialGroup()
                .addGroup(jd_carreteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_carreteraLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel16))
                    .addGroup(jd_carreteraLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_carreteraLayout.setVerticalGroup(
            jd_carreteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_carreteraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(31, 31, 31)
                .addGroup(jd_carreteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_carreteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(sp_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_carreteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_carreteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_termina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButton4)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel5.setText("Nombre");

        jLabel6.setText("Direccion");

        ta_direccionresta.setColumns(20);
        ta_direccionresta.setRows(5);
        jScrollPane2.setViewportView(ta_direccionresta);

        jp_nivelres.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        jp_nivelres.setAutoscrolls(true);

        jLabel7.setText("Nivel de seguridad");

        jButton2.setText("Crear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel8.setText("Creacion de restaurante");

        jLabel9.setText("Categoria");

        cb_categoriares.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chino", "Mexicano", "Italiano", "Comida Rapido" }));
        cb_categoriares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_categoriaresActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        jLabel23.setText("Calificacion");

        javax.swing.GroupLayout jd_restauranteLayout = new javax.swing.GroupLayout(jd_restaurante.getContentPane());
        jd_restaurante.getContentPane().setLayout(jd_restauranteLayout);
        jd_restauranteLayout.setHorizontalGroup(
            jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_restauranteLayout.createSequentialGroup()
                .addGroup(jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jd_restauranteLayout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jd_restauranteLayout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_categoriares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_restauranteLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jButton2)))
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_restauranteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_restauranteLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addGroup(jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_restauranteLayout.createSequentialGroup()
                            .addGroup(jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(52, 52, 52)
                            .addGroup(jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_nombreres, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jd_restauranteLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(34, 34, 34)
                            .addComponent(jp_nivelres, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(55, Short.MAX_VALUE)))
        );
        jd_restauranteLayout.setVerticalGroup(
            jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_restauranteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(11, 11, 11)
                .addGroup(jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cb_categoriares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addGap(27, 27, 27))
            .addGroup(jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_restauranteLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_nombreres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_restauranteLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6))
                        .addGroup(jd_restauranteLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(16, 16, 16)
                    .addGroup(jd_restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jp_nivelres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addContainerGap(114, Short.MAX_VALUE)))
        );

        jLabel22.setText("Escoja el lugar");

        cb_jtree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cancha", "Restaurante", "Carretera" }));
        cb_jtree.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_jtreeItemStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jt_listar.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(jt_listar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_jtreeLayout = new javax.swing.GroupLayout(jd_jtree.getContentPane());
        jd_jtree.getContentPane().setLayout(jd_jtreeLayout);
        jd_jtreeLayout.setHorizontalGroup(
            jd_jtreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jtreeLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel22)
                .addGap(51, 51, 51)
                .addComponent(cb_jtree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_jtreeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_jtreeLayout.setVerticalGroup(
            jd_jtreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jtreeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jd_jtreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cb_jtree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jTree1);

        cb_jtable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cancha", "Restaurante" }));
        cb_jtable.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_jtableItemStateChanged(evt);
            }
        });

        jt_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jt_tabla);

        javax.swing.GroupLayout jd_jtableLayout = new javax.swing.GroupLayout(jd_jtable.getContentPane());
        jd_jtable.getContentPane().setLayout(jd_jtableLayout);
        jd_jtableLayout.setHorizontalGroup(
            jd_jtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jtableLayout.createSequentialGroup()
                .addGroup(jd_jtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_jtableLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(cb_jtable, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_jtableLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jd_jtableLayout.setVerticalGroup(
            jd_jtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jtableLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(cb_jtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cb_list.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_listItemStateChanged(evt);
            }
        });

        jScrollPane7.setViewportView(jl_List);

        jLabel24.setText("Listar");

        javax.swing.GroupLayout jd_listLayout = new javax.swing.GroupLayout(jd_list.getContentPane());
        jd_list.getContentPane().setLayout(jd_listLayout);
        jd_listLayout.setHorizontalGroup(
            jd_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(jd_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listLayout.createSequentialGroup()
                        .addComponent(cb_list, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        jd_listLayout.setVerticalGroup(
            jd_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(cb_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Crear Lugar");

        jMenuItem1.setText("Casa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Restaurante");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Cancha");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        carret.setText("Crear carretera");
        carret.setEnabled(false);

        jMenuItem4.setText("Carretera");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        carret.add(jMenuItem4);

        jMenuBar1.add(carret);

        jMenu1.setText("Listar");

        jMenuItem5.setText("JTree");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("JTable");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("JList");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            String nombre = tf_nombrecasa.getText();
            String direccion = ta_casa.getText();
            int seguridad = (Integer) jp_nivelcasa.getValue();
            Casa c = new Casa(nombre, direccion, seguridad);
            tf_nombrecasa.setText("");
            ta_casa.setText("");
            jp_nivelcasa.setValue((Integer) 1);
            JOptionPane.showMessageDialog(this, "Se ha creado con exito");
            jd_casa.dispose();
            lista.add(c);
            if (lista.size() > 2) {
                carret.setEnabled(true);
            }
        } catch (Exception e) {
            tf_nombrecasa.setText("");
            ta_casa.setText("");
            jp_nivelcasa.setValue((Integer) 1);
            JOptionPane.showMessageDialog(this, "No se pudo crear");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            String nombre = tf_nombreres.getText();
            String direccion = ta_direccionresta.getText();
            int seguridad = (Integer) jp_nivelres.getValue();
            String categoria = cb_categoriares.getSelectedItem().toString();
            int calificaion = (int) jSpinner1.getValue();
            Restaurante c = new Restaurante(categoria, calificaion, nombre, direccion, seguridad);
            tf_nombreres.setText("");
            ta_direccionresta.setText("");
            jp_nivelres.setValue((Integer) 1);
            JOptionPane.showMessageDialog(this, "Se ha creado con exito");
            jd_restaurante.dispose();
            lista.add(c);
            if (lista.size() > 2) {
                carret.setEnabled(true);
            }
        } catch (Exception e) {
            tf_nombreres.setText("");
            ta_direccionresta.setText("");
            jp_nivelres.setValue((Integer) 1);
            JOptionPane.showMessageDialog(this, "No se puedo crear");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void cb_categoriaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_categoriaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_categoriaresActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        try {
            String nombre = jt_nombrecan.getText();
            String direccion = ta_direccioncan.getText();
            int seguridad = (Integer) sp_seguridadcan.getValue();
            String categoria = cb_categoriacan.getSelectedItem().toString();
            String estado;
            if (rb_libre.isSelected()) {
                estado = "Libre";
            } else {
                estado = "Ocupado";
            }
            cancha c = new cancha(categoria, estado, nombre, direccion, seguridad);
            jt_nombrecan.setText("");
            ta_direccioncan.setText("");
            sp_seguridadcan.setValue((Integer) 1);
            JOptionPane.showMessageDialog(this, "Se ha creado con exito");
            jd_cancha.dispose();
            lista.add(c);
            if (lista.size() >= 2) {
                carret.setEnabled(true);
            }
        } catch (Exception e) {
            jt_nombrecan.setText("");
            ta_direccioncan.setText("");
            sp_seguridadcan.setValue((Integer) 1);
            JOptionPane.showMessageDialog(this, "No se pudo crear");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jd_casa.setModal(true);
        jd_casa.pack();
        jd_casa.setLocationRelativeTo(this);
        jd_casa.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        jd_restaurante.setModal(true);
        jd_restaurante.pack();
        jd_restaurante.setLocationRelativeTo(this);
        jd_restaurante.setVisible(true);


    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        try {
            int codigo = cont;
            double distancia = (Double) sp_distancia.getValue();
            Lugar inicio = (Lugar) cb_inicio.getSelectedItem();
            Lugar termina = (Lugar) cb_termina.getSelectedItem();
            cont++;
            Carretera c = new Carretera(codigo, distancia, inicio, termina);
            listac.add(c);
            for (Lugar lugar : lista) {
                if (lugar.equals(inicio)) {
                    lugar.getSalidas().add(c);
                    lugar.getEntradas().add(c);
                }
            }
            JOptionPane.showMessageDialog(this, "Se ha creado con exito");
            jd_carretera.dispose();
        } catch (Exception e) {

        }


    }//GEN-LAST:event_jButton4MouseClicked

    private void cb_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_inicioActionPerformed

    private void cb_inicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_inicioItemStateChanged
        cb_termina.removeAllItems();
        if (evt.getStateChange() !=2) {
            Lugar c = (Lugar) cb_inicio.getSelectedItem();
            DefaultComboBoxModel model = (DefaultComboBoxModel) cb_termina.getModel();
            for (Lugar li : lista) {
                if (li == c) {

                } else {
                    model.addElement(li);

                }
            }
            cb_termina.setModel(model);
        }


    }//GEN-LAST:event_cb_inicioItemStateChanged

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jd_carretera.setModal(true);
        jd_carretera.pack();
        jd_carretera.setLocationRelativeTo(this);

        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_inicio.getModel();

        for (Lugar lugar : lista) {
            if (lugar.getSalidas().size() < 1) {
                model.addElement(lugar);
            }

        }
        jd_carretera.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jd_cancha.setModal(true);
        jd_cancha.pack();
        jd_cancha.setLocationRelativeTo(this);
        jd_cancha.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void cb_jtreeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_jtreeItemStateChanged
        if (evt.getStateChange() == 1) {
            DefaultTreeModel model = (DefaultTreeModel) jt_listar.getModel();
            DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) model.getRoot();
            nodo.removeAllChildren();
        }
        if (evt.getStateChange() == 2) {

            if (cb_jtree.getSelectedItem().equals("Restaurante")) {
                DefaultTreeModel modelo = (DefaultTreeModel) jt_listar.getModel();
                DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) modelo.getRoot();
                int cent = 0;
                for (Lugar lugar : lista) {
                    if (lugar instanceof Restaurante) {
                        for (int i = 0; i < nodo.getChildCount(); i++) {
                            if (nodo.getChildAt(i).equals(((Restaurante) lugar).getCategoria())) {
                                DefaultMutableTreeNode p = new DefaultMutableTreeNode(lista);
                                ((DefaultMutableTreeNode) nodo.getChildAt(i)).add(p);
                                cent = 1;
                            }
                        }
                        if (cent != 1) {
                            DefaultMutableTreeNode n = new DefaultMutableTreeNode(((Restaurante) lugar).getCategoria());
                            DefaultMutableTreeNode p = new DefaultMutableTreeNode(lugar);
                            n.add(p);
                            nodo.add(n);
                        }

                    }
                }
                modelo.reload();
            }
            if (cb_jtree.getSelectedItem().equals("Cancha")) {
                DefaultTreeModel modelo = (DefaultTreeModel) jt_listar.getModel();
                DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) modelo.getRoot();
                int cent = 0;
                for (Lugar lugar : lista) {
                    if (lugar instanceof cancha) {
                        for (int i = 0; i < nodo.getChildCount(); i++) {
                            if (nodo.getChildAt(i).equals(((cancha) lugar).getCategoria())) {
                                DefaultMutableTreeNode p = new DefaultMutableTreeNode(lista);
                                ((DefaultMutableTreeNode) nodo.getChildAt(i)).add(p);
                                cent = 1;
                            }
                        }
                        if (cent != 1) {
                            DefaultMutableTreeNode n = new DefaultMutableTreeNode(((cancha) lugar).getCategoria());
                            DefaultMutableTreeNode p = new DefaultMutableTreeNode(lugar);
                            n.add(p);
                            nodo.add(n);
                        }

                    }
                }
                modelo.reload();
            }
        }
    }//GEN-LAST:event_cb_jtreeItemStateChanged

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jd_jtree.setModal(true);
        jd_jtree.pack();
        jd_jtree.setLocationRelativeTo(this);
        jd_jtree.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void cb_jtableItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_jtableItemStateChanged
        if (evt.getStateChange() == 2) {

            DefaultTableModel model = (DefaultTableModel) jt_tabla.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                model.removeRow(i);
            }
            if (cb_jtable.getSelectedItem().equals("Restaurante")) {
                model.setColumnCount(0);
                model.addColumn("Nombre");
                model.addColumn("Direccion");
                model.addColumn("Seguridad");
                model.addColumn("Categoria");
                model.addColumn("Calificacion");
                model.addColumn("Entrada");
                model.addColumn("Salida");
                for (Lugar s : lista) {
                    if (s instanceof Restaurante) {
                        Object[] row = {s.getNombre(), s.getDireccion(), s.getSecurity(), ((Restaurante) s).getCategoria(), ((Restaurante) s).getCalificacion(), s.getEntradas(), s.getSalidas()};
                        model.addRow(row);
                    }
                }

            }
            if (cb_jtable.getSelectedItem().equals("Cancha")) {
                model.setColumnCount(0);
                model.addColumn("Nombre");
                model.addColumn("Direccion");
                model.addColumn("Seguridad");
                model.addColumn("Categoria");
                model.addColumn("Estado");
                model.addColumn("Entrada");
                model.addColumn("Salida");
                for (Lugar s : lista) {
                    if (s instanceof cancha) {
                        Object[] row = {s.getNombre(), s.getDireccion(), ((cancha) s).getCategoria(), ((cancha) s).getEstado(), s.getEntradas(), s.getSalidas()};
                        model.addRow(row);
                    }
                }
            }
            if (cb_jtable.getSelectedItem().equals("Carretera")) {
                model.setColumnCount(0);
                model.addColumn("Codigo");
                model.addColumn("Distancia");
                model.addColumn("Inicio");
                model.addColumn("Fin");
                for (Object s : listac) {
                    if (s instanceof Carretera) {
                        Object[] row = {((Carretera) s).getCodigo(), ((Carretera) s).getDistancia(), ((Carretera) s).getInicio(), ((Carretera) s).getFinali()};
                        model.addRow(row);
                    }
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_jtableItemStateChanged

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jd_jtable.setModal(true);
        jd_jtable.pack();
        jd_jtable.setLocationRelativeTo(this);
        jd_jtable.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
      jd_list.setModal(true);
      jd_list.pack();
      jd_list.setLocationRelativeTo(this);
      jd_list.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void cb_listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_listItemStateChanged
        DefaultListModel model = (DefaultListModel)jl_List.getModel();
        Lugar c = (Lugar)cb_list.getSelectedItem();
        ArrayList <Carretera>cd = c.getEntradas();
        for (Carretera xc : cd) {
            if (xc.getDistancia()<=50) {
                model.addElement(xc);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_listItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu carret;
    private javax.swing.JComboBox<String> cb_categoriacan;
    private javax.swing.JComboBox<String> cb_categoriares;
    private javax.swing.JComboBox<String> cb_inicio;
    private javax.swing.JComboBox<String> cb_jtable;
    private javax.swing.JComboBox<String> cb_jtree;
    private javax.swing.JComboBox<String> cb_list;
    private javax.swing.JComboBox<String> cb_termina;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTree jTree1;
    private javax.swing.JDialog jd_cancha;
    private javax.swing.JDialog jd_carretera;
    private javax.swing.JDialog jd_casa;
    private javax.swing.JDialog jd_jtable;
    private javax.swing.JDialog jd_jtree;
    private javax.swing.JDialog jd_list;
    private javax.swing.JDialog jd_restaurante;
    private javax.swing.JList<String> jl_List;
    private javax.swing.JSpinner jp_nivelcasa;
    private javax.swing.JSpinner jp_nivelres;
    private javax.swing.JTree jt_listar;
    private javax.swing.JTextField jt_nombrecan;
    private javax.swing.JTable jt_tabla;
    private javax.swing.JRadioButton rb_libre;
    private javax.swing.JRadioButton rb_ocupado;
    private javax.swing.ButtonGroup rbg_estado;
    private javax.swing.JSpinner sp_distancia;
    private javax.swing.JSpinner sp_seguridadcan;
    private javax.swing.JTextArea ta_casa;
    private javax.swing.JTextArea ta_direccioncan;
    private javax.swing.JTextArea ta_direccionresta;
    private javax.swing.JTextField tf_nombrecasa;
    private javax.swing.JTextField tf_nombreres;
    // End of variables declaration//GEN-END:variables
int cont = 1;
    ArrayList<Lugar> lista = new ArrayList();
    ArrayList<Carretera> listac = new ArrayList();
}
